### PR TITLE
Feature show elementid detail

### PR DESCRIPTION
**Pull request by sapiens-code**
### Purpose

get and show element in cell value which return a ElementId

## method value
the method value will display element name
image
if get fail, will display null value
image
## property value
the property value will display in the format <[type] [name] [id]>
image
if get fail, will display -1
image

### Declarations

Check these if you believe they are true

- [x] This PR for new feature

### Reviewers

@chuongmep @weianweigan

### CODE REVIEW

**Comment by chuongmep** [comment]
@sapiens-code  whether we can add feature this support properties include ?

**Comment by sapiens-code** [comment]
> @sapiens-code whether we can add feature this support properties include ?

sure. I can update this feature.

**Comment by chuongmep** [comment]
Thank you very much for this feature, I will wait for you to complete the information with the **properties** and review again code before merge them into branch dev.

**Comment by sapiens-code** [comment]
hi @chuongmep @weianweigan, I have finished the feature of displaying the element for the propẻty, now you can check it out

**Comment by chuongmep** [comment]
Look good for me .

**Comment by chuongmep** [comment]
@weianweigan  you have any problem about pull request this ? if do't have i will merge to dev branch , this is a good feature .

**Pull request merged**
