### PR TITLE
Add Support RevitLookupWpf Interactive in Dynamo Revit

### PR DESCRIPTION
**Pull request by chuongmep**
### Purpose

Add Support Snoop Object From Dynamo Revit

### Description
Allow user use RevitLookup inside dynamo to interactive and snoop, some future is same.This future can use when user install RevitLookupWpf Inside computer, don't need any request special.
User can download from store dynamo package of Autodesk.
image

Some future can use :
- [x] Snoop Element
- [x] Snoop Document
- [x] Snoop Active View
- [x] Snoop By Element Id
- [x] Snoop Object
- [x] Snoop Current Selection

Preview :
image

Note : Some document guideline will be push after this pull request.

image

### Declarations

Check these if you believe they are true

- [ ] This PR fix bug
- [x] This PR for new feature
- [ ] The codebase is in a better state after this PR
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] Snapshot of UI changes, if any.
- [x] This PR modifies some build requirements and the readme is updated

### Reviewers

@weianweigan

### CODE REVIEW

**Comment by weianweigan** [comment]
Nice work! It' a great feature!
I tried it in revit 2023 but it failed.This is my dynamo window picture.

I found that the package version of RevitLookup is 2022.0.1. Is it the reason that i cannot use it in Revit 2023?

image



image

**Comment by chuongmep** [comment]
@weianweigan need install package ironpython 2.7 to can work in revit 2023 at the moment, because I want support for old python first , next will be move to Cpython3.
image

**Comment by chuongmep** [comment]
https://user-images.githubusercontent.com/31106432/186431231-9aed902b-7a70-4836-8ff6-9b7b9f7a3685.mp4

**Comment by weianweigan** [comment]
> @weianweigan need install package ironpython 2.7 to can work in revit 2023 at the moment, because I want support for old python first , next will be move to Cpython3. image

Thanaks for your help. I will retry.

**Comment by weianweigan** [comment]
> > @weianweigan need install package ironpython 2.7 to can work in revit 2023 at the moment, because I want support for old python first , next will be move to Cpython3. image
> 
> Thanaks for your help. I will retry.

It works for me.

**Pull request merged**
