### PR TITLE
Add unitconverter and geometry preview window

### PR DESCRIPTION
**Pull request by weianweigan**
### Purpose

Add unit converter under datagrid;
Send geometry objects to a preivew window;
Use new icon;

### Description

There is a unit conveter bar under datagrid.It will converter some object to meter such as XYZ.
If you click the icon, it will open a tool window so that user can input values.

image

image

When user snooping a geometry object, it will disapear a icon int object tree node.If user clicked this icon, a 3d preview window will be opened.
Support objects:
* GeometryInstance 
* Solid 
* Face 
* Edge 
* Line 
* Curve 
* BoundingBoxXYZ 

image

image

image

### Declarations

Check these if you believe they are true

- [ ] This PR fix bug
- [x] This PR for new feature
- [ ] The codebase is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] Snapshot of UI changes, if any.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@chuongmep 
Sorry that i made so many things in a pr.

### CODE REVIEW

**Comment by chuongmep** [comment]
@weianweigan Can 3D preview support for geometry in Dynamo Revit like surface, curve, line,..?
image

**Comment by weianweigan** [comment]
> 
Thanks for your reply.
I think that it's possible to support geometry object in dynamo revit, but i found Watch3D node can preview geometry object in dynamo.Is there any other advantage that preview dynamo geometry object in another preview window ?

image

**Comment by chuongmep** [comment]
@weianweigan I just question to write feature and limit or feature in README, I believe that we don't need to develop this in Dynamo Revit.

**Comment by weianweigan** [comment]
@chuongmep Yes，I agree with you!🥮🥮🥮

**Comment by weianweigan** [comment]
@chuongmep I get it.It can not  preview dynamo geometry objects.

**Comment by chuongmep** [comment]
> @chuongmep I get it.It can not preview dynamo geometry objects.
@weianweigan do you need to add this feature in this pull request ?

**Comment by weianweigan** [comment]
@chuongmep I don't need add this feature in this pr.I don't have any idea about how to implement it now.

**Pull request merged**
