### PR TITLE
Feature Input Parameters

### PR DESCRIPTION
**Pull request by weianweigan**
### Purpose

Get value from simple methods or properties.

### Description

I made a dropdown control so user can input some simple parameters to get a value.

image

### Declarations

Check these if you believe they are true

- [x] This PR fix bug
- [x] This PR for new feature

### CODE REVIEW

**Comment by chuongmep** [comment]
I think when user click apply, me be we need close expand and if user want input again, need click to button dropdown.
image

**Comment by weianweigan** [comment]
You are right, i will fix this.

**Comment by chuongmep** [comment]
Need sort all BuiltInParameter to quick select, if can, i hope you can fix that because too much BuiltInParameter inside
image

**Comment by weianweigan** [comment]
More than 3000 enum, i can sort by name,but it still so much.Do you have some ideas?

**Comment by chuongmep** [comment]
> More than 3000 enum, i can sort by name,but it still so much.Do you have some ideas?


I think may be we can convert to input by string and if user need more info, can goto revitapidoc.com to check.it my ideas, becuase it effect too much performance of addin.

**Comment by weianweigan** [comment]
I agree. I will change it to a textbox.

**Pull request merged**
