### PR TITLE
Feature doconline

### PR DESCRIPTION
**Pull request by weianweigan**
### Purpose

Use json file to match api doc url. 

### Description

image

More detail see #20 #21

### Declarations

Check these if you believe they are true

- [x] This PR for new feature
- [x] The codebase is in a better state after this PR
- [x] Snapshot of UI changes, if any.

### Reviewers

@chuongmep

### CODE REVIEW

**Comment by chuongmep** [comment]
@weianweigan  i fix some error before merge , if not result in json we will goto online for user.

**Comment by chuongmep** [comment]
Still have some problem, may be we need check this first 
image

**Comment by chuongmep** [comment]
@weianweigan awsome feature

**Comment by weianweigan** [comment]
> Still have some problem with some method have input value , may be we need check this first image

I am sorry that i forget the () in APIName.

**Comment by chuongmep** [comment]
no problem, i will review all and fix it

**Pull request merged**
